### PR TITLE
Add a "Vary" header for DNT, useful for caching.

### PR DESCRIPTION
**Pull request by eillarra**

### CODE REVIEW

**Comment by eillarra** [comment]
@jsocol Can you check this? Thanks!

**Comment by jsocol** [comment]
Hi @eillarra—it might be best to go to the `#webdev` channel on Mozilla IRC. I haven't been with Mozilla for several years (or touched this in exactly 6)

**Comment by jwhitlock** [comment]
I'd say use https://github.com/benspaulding/django-donottrack/, which does have the vary header, but it doesn't look any more maintained.

@jsocol, can you add me to owners on the repo and "John.Whitlock" on PyPI?

**Comment by eillarra** [comment]
@jwhitlock Thanks for the tip, but the repo doesn't seem to be maintained: https://github.com/benspaulding/django-donottrack/pull/1 . Mozilla's repo was the first one I found while Googling, so maybe we can try to bring it back to live...

**Comment by jsocol** [comment]
@jwhitlock Added you on PyPI and removed me, but I don't have admin access to this repo on GH anymore

**Comment by mykmelez** [comment]
> @jwhitlock Added you on PyPI and removed me, but I don't have admin access to this repo on GH anymore

I've given @jwhitlock admin access to this repo, so he should now be able to handle this pull request.

**Review by jwhitlock — APPROVED** [review]
👍 good doc strings, and the vary patch is similar to https://github.com/benspaulding/django-donottrack/blob/master/donottrack/middleware.py

**Pull request merged**
